<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete album';
$url   = $this->url('album-tuto', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($album->title) ?>" by
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">

<div class="form-group">
    <a href="<?=$this->url("album-tuto")?>" class="btn btn-secondary">Back to list</a>

    <input type="hidden" name="id" value="<?= $album->id ?>" />
    <input type="submit" class="btn btn-danger" name="validate_delete" value="Delete" />
    <input type="submit" class="btn btn-success" value="No" />
</div>
</form>