<h3>albums</h3>

<table>
<thead><tr><th></th><th>Artist:</th><th>Title:</th><th></th></tr></thead><tbody>
<?php foreach ($albums as $album): ?>
    <tr>
    <td><?=$this->escapeHtml($album->id)?></td>
    <td><?=$this->escapeHtml($album->artist)?></td>
    <td><?=$this->escapeHtml($album->title)?></td>
    <td>
        <a href="<?=$this->url("album", ['action'=>'edit', 'id'=>$album->id])?>">U</a>
        <a href="<?=$this->url("album", ['action'=>'delete', 'id'=>$album->id])?>">X</a>
    </td>
    </tr>
<?php endforeach ?>

</tbody></table>
<a href="<?=$this->url('blog', ['action'=>'create'])?>" class="btn btn-primary">Create</a>