<div class="msg"><?= $msg??'' ?></div><br/>
<form action="<?= $action ?>" name="user_form" method="post">
    <input type="hidden" name="cn" value="<?=$user['cn']?>"/>
    <input type="hidden" name="onlychange" value=""/>

    <div>Schemas: <select name="objectclass" onchange="this.form.onlychange.value='yes';this.form.submit()">
        <?php foreach($schemas as $name => $data): ?>
            <option value="<?=$name?>" <?= $name==$post['objectclass']?'selected':''?>><?=$name?></option>
        <?php endforeach; ?>
    </select></div>

    <?php if ($schemas[$post['objectclass']]['must']): ?>
        <?php foreach($schemas[$post['objectclass']]['must'] as $value): ?>
            <div>
                <label style="color:red;display:inline-block;width:150px" for="<?= $value ?>"><?= $value ?></label>
                <input type="text" name="<?= $value ?>" value="<?= $post[$value]??'' ?>"/>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($schemas[$post['objectclass']]['may']): ?>
        <?php foreach($schemas[$post['objectclass']]['may'] as $value): ?>
            <div>
                <label style="display:inline-block;width:150px" for="<?= $value ?>"><?= $value ?></label>
                <input type="text" name="<?= $value ?>" value="<?= $post[$value]??'' ?>"/>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <button type="submit"><?= 'create'==$_ctrl_action ? 'Create' : 'Update' ?> data</button>
</form>
