<?php if($user):?>
    <h2>User <?= $user['cn'][0] ?></h2>
    <ul>
        <?php foreach($user as $propertie => $value): ?>
        <li style="list-style-type:none">
            <b style="width:120px;display:inline-block"><?= $propertie ?>:</b> 
            <?= is_string($value)?$value:implode(',',$value) ?>
        </li>
        <?php endforeach; ?>
    </ul>
<?php else: echo 'User doesnt exists' ?>
<?php endif; ?>
<a href="/ldap/user/list">Back to list</a>